export default [
  {
    id: 1,
    brand: "Tokyo Talkies",
    title: "Washed denim Jacket",
    offerPrice: 1034,
    mrp: 3099,
    url: "../Images/gallery-02.jpg",
  },
  {
    id: 2,
      brand: "Tokyo Talkies",
    newSeason:true,
    title: "Cropped Trucker Jacket",
    offerPrice: 1034,
    mrp: 3099,
    url: "../Images/gallery-06.jpg",
  },
  {
    id: 3,
    brand: "Tokyo Talkies",
    title: "Washed denim Jacket",
    offerPrice: 1034,
    mrp: 3099,
    url: "../Images/gallery-06.jpg",
  },
  {
    id: 4,
    brand: "Tokyo Talkies",
    title: "Cropped Trucker Jacket",
    offerPrice: 1034,
    mrp: 3099,
    url: "../Images/gallery-05.jpg",
  },
  {
    id: 5,
    title: "Cropped Trucker Jacket",
    offerPrice: 1034,
    mrp: 3099,
    url: "../Images/gallery-02.jpg",
  },
  {
    id: 6,
    brand: "Tokyo Talkies",
    title: "Cropped Trucker Jacket",
    offerPrice: 1034,
    mrp: 3099,
    url: "../Images/gallery-06.jpg",
  },
  {
    id: 7,
    brand: "Tokyo Talkies",
    title: "Cropped Trucker Jacket",
    offerPrice: 1034,
    mrp: 3099,
    url: "../Images/gallery-05.jpg",
  },
];